apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - spbravo
    environmentGitOwner: spbrvo
    gitKind: github
    gitName: spbravo
    gitServer: https://github.com
    provider: minikube
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: $DOMAIN
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
